const fs = require("fs");
const p = "pages/dashboard/website/invoices.js";
let t = fs.readFileSync(p, "utf8");
const B = String.fromCharCode(92);
function rep(lines, out) {
  for (const nl of ["\r\n", "\n"]) {
    const a = lines.join(nl);
    if (t.includes(a)) { t = t.replace(a, out.join(nl)); return; }
  }
  throw new Error("miss " + lines[0].trim().slice(0, 40));
}

rep([
'          <Field label="Lead">',
'            <select className="lp-in" style={s.input} value={f.leadId} onChange={(e) => set("leadId", e.target.value)}>',
'              <option value="">— pick a lead —</option>',
'              {leads.map((l) => (',
'                <option key={l._id} value={l._id}>{leadRef(l._id)} · {l.businessName || l.name}</option>',
'              ))}',
'            </select>',
'          </Field>',
'          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>',
'            <Field label="For">',
'              <select className="lp-in" style={s.input} value={f.kind} onChange={(e) => set("kind", e.target.value)}>',
'                {KINDS.map((x) => <option key={x} value={x}>{x}</option>)}',
'              </select>',
'            </Field>',
'            <Field label="Service">',
'              <select className="lp-in" style={s.input} value={f.svc} onChange={(e) => set("svc", e.target.value)}>',
'                <option value="">—</option>',
'                {svcList.map((x) => <option key={x} value={x}>{x}</option>)}',
'              </select>',
'            </Field>',
'            <Field label="Amount (₹)">',
'              <input className="lp-in" style={s.input} inputMode="numeric" value={f.amount}',
'                     onChange={(e) => set("amount", e.target.value.replace(/' + B + 'D/g, ""))} />',
'            </Field>',
'            <Field label="GST %">',
'              <input className="lp-in" style={s.input} inputMode="numeric" value={f.gstPct}',
'                     onChange={(e) => set("gstPct", e.target.value.replace(/' + B + 'D/g, "").slice(0, 2))} />',
'            </Field>',
'            <Field label="Issued">',
'              <input className="lp-in" style={s.input} type="date" value={f.issued} onChange={(e) => set("issued", e.target.value)} />',
'            </Field>',
'            <Field label="Due">',
'              <input className="lp-in" style={s.input} type="date" value={f.due} onChange={(e) => set("due", e.target.value)} />',
'            </Field>',
'          </div>',
'          <Field label="Owner">',
'            <input className="lp-in" style={s.input} value={f.owner} onChange={(e) => set("owner", e.target.value)} />',
'          </Field>',
], [
'          <Field label="Lead" hint="Picking one fills the billing details in; all of them can be typed over.">',
'            <select className="lp-in" style={s.input} value={f.leadId} onChange={(e) => set("leadId", e.target.value)}>',
'              <option value="">— pick a lead —</option>',
'              {leads.map((l) => (',
'                <option key={l._id} value={l._id}>{leadRef(l._id)} · {l.businessName || l.name}</option>',
'              ))}',
'            </select>',
'          </Field>',
'',
'          <Section n="Billed to" />',
'          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>',
'            <Field label="Company">',
'              <input className="lp-in" style={s.input} value={f.co} onChange={(e) => set("co", e.target.value)} placeholder="Who the bill is addressed to" />',
'            </Field>',
'            <Field label="Contact person">',
'              <input className="lp-in" style={s.input} value={f.contact} onChange={(e) => set("contact", e.target.value)} />',
'            </Field>',
'            <Field label="Email">',
'              <input className="lp-in" style={s.input} type="email" value={f.em} onChange={(e) => set("em", e.target.value)} />',
'            </Field>',
'            <Field label="Phone">',
'              <input className="lp-in" style={s.input} value={f.ph} onChange={(e) => set("ph", e.target.value)} />',
'            </Field>',
'          </div>',
'          <Field label="Billing address">',
'            <input className="lp-in" style={s.input} value={f.address} onChange={(e) => set("address", e.target.value)}',
'                   placeholder="Street, building, floor" />',
'          </Field>',
'          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10 }}>',
'            <Field label="City">',
'              <input className="lp-in" style={s.input} value={f.city} onChange={(e) => set("city", e.target.value)} />',
'            </Field>',
'            <Field label="State" hint="Decides CGST + SGST or IGST.">',
'              <input className="lp-in" style={s.input} value={f.state} onChange={(e) => set("state", e.target.value)} />',
'            </Field>',
'            <Field label="Pincode">',
'              <input className="lp-in" style={s.input} inputMode="numeric" value={f.pincode}',
'                     onChange={(e) => set("pincode", e.target.value.replace(/' + B + 'D/g, "").slice(0, 6))} />',
'            </Field>',
'          </div>',
'          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>',
'            <Field label="Their GSTIN">',
'              <input className="lp-in" style={s.input} value={f.gstin}',
'                     onChange={(e) => set("gstin", e.target.value.toUpperCase().slice(0, 15))} placeholder="Optional" />',
'            </Field>',
'            <Field label="PO / reference">',
'              <input className="lp-in" style={s.input} value={f.poRef} onChange={(e) => set("poRef", e.target.value)}',
'                     placeholder="Their purchase order, if there is one" />',
'            </Field>',
'          </div>',
'',
'          <Section n="What is being billed" />',
'          <ServiceLines items={items} setItems={setItems} svcList={svcList} ui={s} label="Lines on this invoice" />',
'',
'          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>',
'            <Field label="For">',
'              <select className="lp-in" style={s.input} value={f.kind} onChange={(e) => set("kind", e.target.value)}>',
'                {KINDS.map((x) => <option key={x} value={x}>{x}</option>)}',
'              </select>',
'            </Field>',
'            <Field label="GST %">',
'              <input className="lp-in" style={s.input} inputMode="numeric" value={f.gstPct}',
'                     onChange={(e) => set("gstPct", e.target.value.replace(/' + B + 'D/g, "").slice(0, 2))} />',
'            </Field>',
'            <Field label="Issued">',
'              <input className="lp-in" style={s.input} type="date" value={f.issued} onChange={(e) => set("issued", e.target.value)} />',
'            </Field>',
'            <Field label="Due">',
'              <input className="lp-in" style={s.input} type="date" value={f.due} onChange={(e) => set("due", e.target.value)} />',
'            </Field>',
'          </div>',
'',
'          {sub ? (',
'            <div style={{ ...s.softBox, marginBottom: 12 }}>',
'              <KV k="Subtotal" v={inr(sub)} />',
'              <KV k={`GST ${f.gstPct || 0}%`} v={inr(tax)} />',
'              <KV k="Invoice total" v={inr(sub + tax)} />',
'            </div>',
'          ) : null}',
'',
'          <Field label="Owner">',
'            <input className="lp-in" style={s.input} value={f.owner} onChange={(e) => set("owner", e.target.value)} />',
'          </Field>',
'          <Field label="Notes on the invoice">',
'            <textarea className="lp-in" style={{ ...s.input, height: 70, padding: "9px 11px", resize: "vertical" }}',
'                      value={f.notes} onChange={(e) => set("notes", e.target.value)}',
'                      placeholder="Anything the client should read on the bill" />',
'          </Field>',
]);

fs.writeFileSync(p, t);
console.log("ok");
